/*
 * cryptpe -- Encryption tool for PE binaries
 * (C) 2012 Martin Wolters
 *
 * This program is free software. It comes without any warranty, to
 * the extent permitted by applicable law. You can redistribute it
 * and/or modify it under the terms of the Do What The Fuck You Want
 * To Public License, Version 2, as published by Sam Hocevar. See
 * http://sam.zoy.org/wtfpl/COPYING for more details.
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "..\shared\types.h"
#include "..\shared\rc4.h"
#include "..\shared\rc4_key.h"

#include "huffman_enc.h"

#if RC4_KEY == 1234
#error Set the RC4 key in rc4_key.h first
#endif

int main(int argc, char **argv) {
	rc4_ctx_t rc4_ctx;
	uchar rc4_buf[320], *file_buf, *enc_tree, *encoded;
	size_t c, pos = 0, file_size, tree_size;
	hfm_node_t *root;
	hfm_cdb_t *codebook;
	FILE *fp;

	rc4_ctx = rc4_init((uchar*)RC4_KEY, strlen(RC4_KEY));
	rc4_drop(3072, &rc4_ctx);

	if(argc == 1) {
		fprintf(stderr, "USAGE: %s <FILENAME>\n", argv[0]);
		return EXIT_FAILURE;
	}

	if((fp = fopen(argv[1], "rb")) == NULL) {
		fprintf(stderr, "ERROR: Could not open '%s'.\n", argv[1]);
		return EXIT_FAILURE;
	}
	
	printf("/* THIS FILE HAS BEEN AUTOMATICALLY GENERATED BY MKBINTABLE */\n\n");
	printf("#include \"..\\shared\\types.h\"\n\n");
	printf("#ifndef BINTABLE_H_\n");
	printf("#define BINTABLE_H_\n\n");

	fseek(fp, 0, SEEK_END);
	file_size = ftell(fp);
	file_buf = malloc(file_size);
	fseek(fp, 0, SEEK_SET);
	fread(file_buf, file_size, 1, fp);

	printf("size_t file_size = %d;\n\n", file_size);

	root = maketree(file_buf, file_size);
	enc_tree = encode_tree(root, &tree_size);

	rc4_gen(rc4_buf, 320, &rc4_ctx);
	printf("uchar tree[] = {");
	for(c = 0; c < tree_size; c++) {
		if(!(c % 32))
			printf("\n\t");

		printf("0x%02x", enc_tree[c] ^ rc4_buf[c]);
		if(c < (tree_size - 1))
			printf(", ");
	}
	printf("\n};\n\n");	
	
	codebook = make_codebook(root);
	encoded = encode(file_buf, file_size, codebook, &file_size);
	
	printf("uchar binary[] = {");
	for(c = 0; c < file_size; c++) {
		if(!(c % 32))
			printf("\n\t");
		if(!(c % 320))
			rc4_gen(rc4_buf, 320, &rc4_ctx);

		printf("0x%02x", encoded[c] ^ rc4_buf[c % 320]);
		if(c < (file_size - 1))
			printf(", ");
	}
	printf("\n};\n\n");
	

	printf("#endif\n");


	free(codebook);
	free(enc_tree);
	free(file_buf);
	free_tree(root);
	fclose(fp);

	return EXIT_SUCCESS;
} 
